### ISSUE TITLE
Output file not parsed by bcftools

### ISSUE THREAD

**Issue by gariem** [ndierckx/combiSV#2]
Thanks for the merger, it seems very interesting. I'm testing it as part of a series of experiments and I was able to generate a merge file taking both sniffles and pbsv calls as input. The resulting merged file looks like:

```
##fileformat=VCFv4.2
##fileDate=Thu Jan  6 00:17:44 2022
##source=combiSV-v1.1
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=INS,Description="Insertion">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVCALLERS,Number=.,Type=String,Description="SV callers that support this SV">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHR	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample
1	4835887	id.1	N	<INS>	.	PASS	SVTYPE=INS;SVLEN=91;SVCALLERS=Sniffles	GT	0/1
1	5143557	id.2	N	<INS>	.	PASS	SVTYPE=INS;SVLEN=46;SVCALLERS=Sniffles,pbsv	GT	1/1
1	5447682	id.3	N	<DEL>	.	PASS	SVTYPE=DEL;SVLEN=84;SVCALLERS=Sniffles,pbsv	GT	1/1
1	5590869	id.4	N	<INS>	.	PASS	SVTYPE=INS;SVLEN=176;SVCALLERS=Sniffles,pbsv	GT	1/1
1	5687948	id.5	N	<INS>	.	PASS	SVTYPE=INS;SVLEN=76;SVCALLERS=Sniffles,pbsv	GT	1/1
.
.
.
[file continues]
```
But... for some reason bcftools fails to parse it:

`bcftools query -i"CHR='1'" -f'%CHR\t%POS\t%SVTYPE\n' combi-out.vcf`
```

[W::bcf_hdr_parse] Could not parse header line: "#CHR\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSample"
[E::bcf_hdr_parse] Could not parse the header, sample line not found
Failed to read from ./data/input/DBA_2J-combisv.vcf: could not parse header
```

Also, it would be better to keep the header as the other callers (CHROM instead of CHR and maybe add an END info field.
Finally, the version in the top of the file is also incorrect, as I used the latest version (2.1)

Thanks in advance!

**Comment by gariem** [comment]
I changed the header and updated the version. Feel free to automatically merge the changes in this PR: https://github.com/ndierckx/combiSV/pull/3 
Have a nice day!

**Comment by ndierckx** [comment]
Hi,

Thanks for the fix, now it works for bcftools?
And I haven't tested it much for merging two callers, I generally add three
I would recommend to also add cuteSV, it is fast and easy to use and install.

**Comment by gariem** [comment]
Everything is fine now, bcftools don't have any issues reading the other fields. I will try cuteSV too, thanks!

**Comment by ndierckx** [comment]
I didn't had time before but I added the END position and also the allele depth counts (DR and DV)
